from __future__ import annotations

from io import StringIO
from pathlib import Path

import pytest

from app.database.base import Base
from app.database.session import create_engine_from_url, create_session_factory
from app.domains.commercial.entities import (
    CommissionStatus,
    CommercialVertical,
    ConversionStatus,
)
from app.domains.commercial.orm import OutboundClickRow
from app.domains.commercial.reconciliation import (
    CanonicalCommissionCsvError,
    CommissionReconciliationService,
    load_canonical_commission_csv,
)
from app.domains.commercial.repository import SqlAlchemyCommercialRepository
from app.domains.commercial.service import CommercialLedgerService


HEADER = (
    "partner_slug,programme_name,transaction_reference,click_sub_id,gross_value,"
    "commission_amount,currency,conversion_status,commission_status,"
    "commission_reference,booked_at,approved_at,paid_at,source\n"
)


@pytest.fixture
def reconciliation_database(tmp_path: Path):
    engine = create_engine_from_url(f"sqlite+pysqlite:///{tmp_path / 'reconciliation.db'}")
    Base.metadata.create_all(engine)
    factory = create_session_factory(engine)
    with factory.begin() as session:
        repository = SqlAlchemyCommercialRepository(session)
        ledger = CommercialLedgerService(repository)
        partner = ledger.register_partner(
            slug="expedia",
            name="Expedia",
            website_url="https://www.expedia.com",
        )
        programme = ledger.register_programme(
            partner_id=partner.id,
            name="Expedia UK",
            vertical=CommercialVertical.ACCOMMODATION,
            tracking_template="https://www.expedia.com/?aff={affiliate_id}",
            affiliate_identifier="mZObD29",
            default_currency="GBP",
        )
        click = ledger.record_click(
            programme_id=programme.id,
            destination_url="https://www.expedia.com/Hotel-Search",
            tracking_url="https://www.expedia.com/?aff=mZObD29",
        )
        # Reconciliation uses the click sub-ID generated by the safe-link path.
        click.sub_id = "trip-42"
        row = session.get(OutboundClickRow, click.id)
        row.sub_id = click.sub_id
    yield factory
    engine.dispose()


def _rows(
    *,
    conversion_status: str = "PENDING",
    commission_status: str = "EXPECTED",
    commission_amount: str = "42.03",
    click_sub_id: str = "trip-42",
):
    return load_canonical_commission_csv(StringIO(
        HEADER
        + f"expedia,Expedia UK,booking-123,{click_sub_id},840.50,{commission_amount},GBP,"
        + f"{conversion_status},{commission_status},commission-123,"
        + "2026-07-19T09:00:00Z,,,expedia\n"
    ))


def test_reconciliation_creates_conversion_commission_and_matches_click(
    reconciliation_database,
):
    with reconciliation_database.begin() as session:
        repository = SqlAlchemyCommercialRepository(session)
        summary = CommissionReconciliationService(repository).reconcile(_rows())
        assert summary.successful == 1
        assert summary.conversions_created == 1
        assert summary.commissions_created == 1
        assert summary.clicks_matched == 1
        assert repository.counts()["conversions"] == 1
        assert repository.counts()["commissions"] == 1


def test_repeated_report_is_idempotent_and_updates_status(reconciliation_database):
    with reconciliation_database.begin() as session:
        repository = SqlAlchemyCommercialRepository(session)
        service = CommissionReconciliationService(repository)
        service.reconcile(_rows())
        summary = service.reconcile(_rows(
            conversion_status="CONFIRMED",
            commission_status="APPROVED",
            commission_amount="50.00",
        ))
        assert summary.conversions_updated == 1
        assert summary.commissions_updated == 1
        assert repository.counts()["conversions"] == 1
        assert repository.counts()["commissions"] == 1
        partner = repository.get_partner_by_slug("expedia")
        programme = repository.get_programme_by_partner_and_name(partner.id, "Expedia UK")
        conversion = repository.get_conversion_by_external_reference(
            programme.id, "booking-123"
        )
        commission = repository.get_commission_by_external_reference("commission-123")
        assert conversion.status == ConversionStatus.CONFIRMED
        assert commission.status == CommissionStatus.APPROVED
        assert str(commission.amount) == "50.00"


def test_unmatched_sub_id_is_reported_without_rejecting_sale(reconciliation_database):
    with reconciliation_database.begin() as session:
        summary = CommissionReconciliationService(
            SqlAlchemyCommercialRepository(session)
        ).reconcile(_rows(click_sub_id="unknown-click"))
        assert summary.successful == 1
        assert summary.clicks_unmatched == 1
        assert summary.conversions_created == 1


def test_terminal_paid_commission_cannot_regress(reconciliation_database):
    with reconciliation_database.begin() as session:
        service = CommissionReconciliationService(SqlAlchemyCommercialRepository(session))
        service.reconcile(_rows(
            conversion_status="CONFIRMED",
            commission_status="PAID",
        ))
        summary = service.reconcile(_rows(
            conversion_status="CONFIRMED",
            commission_status="EXPECTED",
        ))
        assert summary.successful == 0
        assert summary.issues[0].message == "terminal commission status cannot be regressed"


def test_unknown_programme_is_a_row_issue(reconciliation_database):
    rows = load_canonical_commission_csv(StringIO(
        HEADER
        + "expedia,Unknown,booking-123,,840.50,42.03,GBP,PENDING,EXPECTED,"
        + "commission-123,2026-07-19T09:00:00Z,,,expedia\n"
    ))
    with reconciliation_database.begin() as session:
        summary = CommissionReconciliationService(
            SqlAlchemyCommercialRepository(session)
        ).reconcile(rows)
        assert summary.successful == 0
        assert summary.issues[0].message == "affiliate programme is not configured"


def test_csv_rejects_unknown_columns_to_avoid_accidental_personal_data_import():
    with pytest.raises(CanonicalCommissionCsvError, match="unsupported columns: email"):
        load_canonical_commission_csv(StringIO(
            HEADER.rstrip("\n") + ",email\n"
            "expedia,Expedia UK,booking-123,,840.50,42.03,GBP,PENDING,EXPECTED,"
            "commission-123,2026-07-19T09:00:00Z,,,expedia,person@example.com\n"
        ))


@pytest.mark.parametrize(
    "replacement, message",
    (
        ("-1.00,42.03", "gross value must be non-negative"),
        ("840.50,42.001", "commission amount must be non-negative"),
        ("840.50,42.03,GB", "currency must be a three-letter ISO code"),
    ),
)
def test_csv_rejects_invalid_money_and_currency(replacement, message):
    prefix = "expedia,Expedia UK,booking-123,,"
    if replacement.endswith(",GB"):
        values = replacement + ",PENDING,EXPECTED"
    else:
        values = replacement + ",GBP,PENDING,EXPECTED"
    with pytest.raises(CanonicalCommissionCsvError, match=message):
        load_canonical_commission_csv(StringIO(
            HEADER
            + prefix + values
            + ",commission-123,2026-07-19T09:00:00Z,,,expedia\n"
        ))


def test_only_import_source_metadata_is_stored(reconciliation_database):
    with reconciliation_database.begin() as session:
        repository = SqlAlchemyCommercialRepository(session)
        CommissionReconciliationService(repository).reconcile(_rows())
        partner = repository.get_partner_by_slug("expedia")
        programme = repository.get_programme_by_partner_and_name(partner.id, "Expedia UK")
        conversion = repository.get_conversion_by_external_reference(
            programme.id, "booking-123"
        )
        assert conversion.conversion_metadata == {"import_source": "expedia"}
